
const street = [
    "Avenida Alexios Jafet, Perus, ",
    "Avenida Domingos Antônio di Sandro, Perus, ",
    "Avenida Doutor Sylvio de Campos, Perus, ",
    "Avenida Fiorelli Peccicacco, Perus, ",
    "Avenida Fortunata Tadielli Natucci, Perus, ",
    "Avenida Marginal, Perus, ",
    "Avenida Pavão, Perus, ",
    "Avenida Raimundo Pereira de Magalhães, Perus, ",
    "Avenida Raimundo Pereira de Magalhães, Perus, ",
    "Caminho 8, Perus, ",
    "Caminho Omar Bradley, Perus, ",
    "Estrada Clementina Cardoso da Silva, Perus, ",
    "Estrada Cleonice Kammer Di Sandro, Perus, ",
    "Estrada da Pedreira, Perus, ",
    "Estrada da Ponte Seca, Perus, ",
    "Estrada di Sandro, Perus, ",
    "Estrada do Pinheirinho, Perus, ",
    "Estrada José Lopes, Perus, ",
    "Estrada São Paulo Jundiai, Perus, ",
    "Praça Campo Lindo, Perus, ",
    "Praça Flor da Imperatriz, Perus, ",
    "Praça Inácio Dias, Perus, ",
    "Ramo A, Perus, ",
    "Rua A, Perus, ",
    "Rua Acapu, Perus, ",
    "Rua Aiparuca, Perus, ",
    "Rua Aipim, Perus, ",
    "Rua Alabano, Perus, ",
    "Rua Alagoa Nova, Perus, ",
    "Rua Alamar, Perus, ",
    "Rua Aldeia de Pedra, Perus, ",
    "Rua Alelu, Perus, ",
    "Rua Almofada, Perus, ",
    "Rua Ana Maria Franco Laranjeira, Perus, ",
    "Rua Anari, Perus, ",
    "Rua Andorinha, Perus, ",
    "Rua André Álvares do Amaral, Perus, ",
    "Rua Antônio Bartolomeu, Perus, ",
    "Rua Antônio Cândido da Rocha, Perus, ",
    "Rua Antônio Cândido de Alvarenga, Perus, ",
    "Rua Antônio da Silva Santos, Perus, ",
    "Rua Antônio de Pádua Dias, Perus, ",
    "Rua Antônio Freire de Menezes, Perus, ",
    "Rua Antônio Joaquim de Mello, Perus, ",
    "Rua Antônio José Anacleto, Perus, ",
    "Rua Antônio Justiano, Perus, ",
    "Rua Antônio Maia, Perus, ",
    "Rua Antônio Paranhos, Perus, ",
    "Rua Antonieta Maia, Perus, ",
    "Rua Anturio Rosa, Perus, ",
    "Rua Aquiles Neto, Perus, ",
    "Rua Aquilino Ribeiro, Perus, ",
    "Rua Aracagi, Perus, ",
    "Rua Argélia, Perus, ",
    "Rua Aristeu, Perus, ",
    "Rua Arisudoro, Perus, ",
    "Rua Armando Correia, Perus, ",
    "Rua Arunta, Perus, ",
    "Rua Augusto Valério do Sacramento, Perus, ",
    "Rua Aurora Boreal, Perus, ",
    "Rua Avestruz, Perus, ",
    "Rua Axibi, Perus, ",
    "Rua Águas Claras do Sul, Perus, ",
    "Rua Árvore de São Tomás, Perus, ",
    "Rua Bagageiro, Perus, ",
    "Rua Bairro da Imbuia, Perus, ",
    "Rua Banana-Branca, Perus, ",
    "Rua Bananal do Rio, Perus, ",
    "Rua Bananalzinho, Perus, ",
    "Rua Barão Geraldo de Rezende, Perus, ",
    "Rua Baruare, Perus, ",
    "Rua Beija Flor, Perus, ",
    "Rua Bem-Aceito, Perus, ",
    "Rua Bem-Te-Vi, Perus, ",
    "Rua Bem-Te-Vi, Perus, ",
    "Rua Benedito Antônio de Luz, Perus, ",
    "Rua Benedito Aparecido da Silva, Perus, ",
    "Rua Bernarda de Lacerda, Perus, ",
    "Rua Bernardo José de Lorena, Perus, ",
    "Rua Binga, Perus, ",
    "Rua Bom Destino, Perus, ",
    "Rua Bom Lugar, Perus, ",
    "Rua Bondade, Perus, ",
    "Rua Bondade, Perus, ",
    "Rua Brasil, Perus, ",
    "Rua Braz Baltazar da Silveira, Perus, ",
    "Rua Brioso, Perus, ",
    "Rua Brotas de Macaúbas, Perus, ",
    "Rua C, Perus, ",
    "Rua Caçado, Perus, ",
    "Rua Campo do Olival, Perus, ",
    "Rua Canadá, Perus, ",
    "Rua Canário, Perus, ",
    "Rua Canhoba, Perus, ",
    "Rua Carcino, Perus, ",
    "Rua Carlos Carneiro de Campos, Perus, ",
    "Rua Carlos Marin, Perus, ",
    "Rua Carlos Santos Xavier de Moraes, Perus, ",
    "Rua Cavalo Marinho, Perus, ",
    "Rua Cândido Afonso Camargo, Perus, ",
    "Rua César de Castro, Perus, ",
    "Rua Cercira, Perus, ",
    "Rua Cesário de Miranda Ribeiro, Perus, ",
    "Rua Chambourcy, Perus, ",
    "Rua Charles, Perus, ",
    "Rua Cipriano Moreira, Perus, ",
    "Rua Clóvis Cavalcanti, Perus, ",
    "Rua Cleonice Kammer di Sandro, Perus, ",
    "Rua Coronel Julião de Moura Negrão, Perus, ",
    "Rua Cosme dos Santos, Perus, ",
    "Rua Creonte, Perus, ",
    "Rua Crispim do Amaral, Perus, ",
    "Rua Cuitegi, Perus, ",
    "Rua Curruira, Perus, ",
    "Rua D, Perus, ",
    "Rua da Conquista, Perus, ",
    "Rua da Ladeira, Perus, ",
    "Rua da Mina, Perus, ",
    "Rua das Araras, Perus, ",
    "Rua das Araras, Perus, ",
    "Rua das Lágrimas, Perus, ",
    "Rua Dedalion, Perus, ",
    "Rua Demétrio Vidal Lopes, Perus, ",
    "Rua Demifonte, Perus, ",
    "Rua Deoclídes Brito, Perus, ",
    "Rua Dinamarca, Perus, ",
    "Rua do Bamburral, Perus, ",
    "Rua do Príncipe Atlântico, Perus, ",
    "Rua Dois, Perus, ",
    "Rua Dom Lino Deodato de Carvalho, Perus, ",
    "Rua Dona Olivia, Perus, ",
    "Rua Dona Rosina, Perus, ",
    "Rua dos Heraclidas, Perus, ",
    "Rua dos Salmistas, Perus, ",
    "Rua Doutor João Rodrigues de Abreu, Perus, ",
    "Rua Doutor José Pacheco e Silva, Perus, ",
    "Rua Doutor Oscar Cunha Correia, Perus, ",
    "Rua Edelcio, Perus, ",
    "Rua Elísio Fonseca, Perus, ",
    "Rua Eleusis, Perus, ",
    "Rua Elisa Pedroso, Perus, ",
    "Rua Embaixador Alexandre Conty, Perus, ",
    "Rua Enéias Galvão, Perus, ",
    "Rua Engenheiro Augusto Durante, Perus, ",
    "Rua Engenheiro Nogueira Soares, Perus, ",
    "Rua Ernersto Diogo de Faria, Perus, ",
    "Rua Ernesto Bottoni, Perus, ",
    "Rua Ernesto Diogo de Faria, Perus, ",
    "Rua Esmirna, Perus, ",
    "Rua Estados Unidos, Perus, ",
    "Rua Estevan Ribeiro Resende, Perus, ",
    "Rua Estrada do Mestre, Perus, ",
    "Rua Eugênia Câmara, Perus, ",
    "Rua Eurides Lopes de Albuquerque, Perus, ",
    "Rua Falero, Perus, ",
    "Rua Felipe Cardoso de Campos, Perus, ",
    "Rua Figueiredo Coimbra, Perus, ",
    "Rua Filgueiras Lima, Perus, ",
    "Rua Filomena Fongaro, Perus, ",
    "Rua Fiorelli Peccicacco, Perus, ",
    "Rua França, Perus, ",
    "Rua Francesco Mosto, Perus, ",
    "Rua Francis de Castelnau, Perus, ",
    "Rua Francisco Araújo Correa, Perus, ",
    "Rua Francisco Badaró, Perus, ",
    "Rua Francisco Gaspar, Perus, ",
    "Rua Francisco José de Barros, Perus, ",
    "Rua Francisco Mariano da Cunha, Perus, ",
    "Rua Francisco Rodrigues Penteado, Perus, ",
    "Rua Francisco Soriano, Perus, ",
    "Rua Frei Marcos de Lisboa, Perus, ",
    "Rua Gaivotas, Perus, ",
    "Rua Gavião, Perus, ",
    "Rua Genesis, Perus, ",
    "Rua George Sarmento, Perus, ",
    "Rua Gofredo, Perus, ",
    "Rua Gomes Leite, Perus, ",
    "Rua Gonçalves de Andrade, Perus, ",
    "Rua Gorgias, Perus, ",
    "Rua Grandes Rios, Perus, ",
    "Rua Grauben do Monte Lima, Perus, ",
    "Rua Grécia, Perus, ",
    "Rua Gualterio, Perus, ",
    "Rua Guilherme Correia de Melo, Perus, ",
    "Rua Hamilton de Araújo, Perus, ",
    "Rua Horácio Cartier, Perus, ",
    "Rua Horácio Mendes Campos, Perus, ",
    "Rua Ibirite, Perus, ",
    "Rua Igaci, Perus, ",
    "Rua Ilha da Vitória, Perus, ",
    "Rua Ilha de Gale, Perus, ",
    "Rua Ilha do Frade, Perus, ",
    "Rua Ilha do Frade, Perus, ",
    "Rua Ilha dos Lobos, Perus, ",
    "Rua Ilha Três Irmãos, Perus, ",
    "Rua India, Perus, ",
    "Rua Ipecaeta, Perus, ",
    "Rua Ipumirim, Perus, ",
    "Rua Irineópolis, Perus, ",
    "Rua Irituia, Perus, ",
    "Rua Itaguaru, Perus, ",
    "Rua Iuna, Perus, ",
    "Rua Jacunaum, Perus, ",
    "Rua Jamaica, Perus, ",
    "Rua Júlio César Leal, Perus, ",
    "Rua Júlio Maciel, Perus, ",
    "Rua Júlio Maciel, Perus, ",
    "Rua Jesuíno Cássia de Lustosa, Perus, ",
    "Rua Joanina Fanton, Perus, ",
    "Rua Joaquim Antônio Arruda, Perus, ",
    "Rua Joaquim da Costa Penha, Perus, ",
    "Rua Joaquim de Araújo Leite, Perus, ",
    "Rua Joaquim de Monte Carmelo, Perus, ",
    "Rua Joaquim de Sousa, Perus, ",
    "Rua Joaquim de Souza Aranha, Perus, ",
    "Rua Joaquim José de Almeida, Perus, ",
    "Rua Joaquim Lopes Guimarães, Perus, ",
    "Rua Joaquim Teodoro Tavares, Perus, ",
    "Rua Joaquim Xavier Pinheiro, Perus, ",
    "Rua João Batista Fanton, Perus, ",
    "Rua João de Barro, Perus, ",
    "Rua João Guedes de Melo, Perus, ",
    "Rua João Jacinto de Mendonça, Perus, ",
    "Rua João Joaquim Alão, Perus, ",
    "Rua João José de Godoi, Perus, ",
    "Rua João Justiniano da Silva, Perus, ",
    "Rua João Justiniano da Silva, Perus, ",
    "Rua João Lener, Perus, ",
    "Rua João Leonel dos Santos, Perus, ",
    "Rua João Pinto Ferreira, Perus, ",
    "Rua João Vicente Valadão, Perus, ",
    "Rua Jordão do Canto e Silva, Perus, ",
    "Rua Jorn Paul Hateyer, Perus, ",
    "Rua José Adami, Perus, ",
    "Rua José Brito Mendes, Perus, ",
    "Rua José Correia Picanco, Perus, ",
    "Rua José Gomes Segurado, Perus, ",
    "Rua Juriti, Perus, ",
    "Rua Juvêncio de Araújo Figueiredo, Perus, ",
    "Rua Lago Huron, Perus, ",
    "Rua Laurindo Leão, Perus, ",
    "Rua Líber, Perus, ",
    "Rua Lívio de Castro, Perus, ",
    "Rua Leão Meneghini, Perus, ",
    "Rua Licínio Cardoso, Perus, ",
    "Rua Lucilo Bueno, Perus, ",
    "Rua Luis Antônio Burgain, Perus, ",
    "Rua Luis Carlos de Assumpção, Perus, ",
    "Rua Luis Nogueira, Perus, ",
    "Rua Magalhães Lemos, Perus, ",
    "Rua Manitoba, Perus, ",
    "Rua Manuel Felizardo de Souza, Perus, ",
    "Rua Manuel Teixeira, Perus, ",
    "Rua Mar do Labrador, Perus, ",
    "Rua Marcelino Ferreira Bueno, Perus, ",
    "Rua Marcondes de Moura e Costa, Perus, ",
    "Rua Margarida Rainha, Perus, ",
    "Rua Maria Caruso Bueno Brandão, Perus, ",
    "Rua Maria de Oliveira Faria, Perus, ",
    "Rua Maria Felicia Malabrin, Perus, ",
    "Rua Marim Lobo de Saldanha, Perus, ",
    "Rua Miguel Vilela, Perus, ",
    "Rua Mogeiro, Perus, ",
    "Rua Monte Sinai, Perus, ",
    "Rua Nandiras, Perus, ",
    "Rua Narciso Degrande, Perus, ",
    "Rua Nicola Vicentino, Perus, ",
    "Rua Nilo Bruzzi, Perus, ",
    "Rua Olímpio Francisco Pedreiro, Perus, ",
    "Rua Orco, Perus, ",
    "Rua Orlando Peccicacco, Perus, ",
    "Rua Padre Diogo Antônio Feijó, Perus, ",
    "Rua Padre Manuel Campello, Perus, ",
    "Rua Papagaio, Perus, ",
    "Rua Paulino Cabral, Perus, ",
    "Rua Paulo Lacombe, Perus, ",
    "Rua Pedro Flores, Perus, ",
    "Rua Pedro Vicente de Azevedo, Perus, ",
    "Rua Perla, Perus, ",
    "Rua Pica Pau, Perus, ",
    "Rua Pinho Leal, Perus, ",
    "Rua Pirabebe, Perus, ",
    "Rua Polifontes, Perus, ",
    "Rua Presidente Vargas, Perus, ",
    "Rua Princesa Diana, Perus, ",
    "Rua Principal, Perus, ",
    "Rua Professor Augusto Nobre, Perus, ",
    "Rua Raphael di Sandro, Perus, ",
    "Rua Recanto dos Humildes, Perus, ",
    "Rua Reynaldo Junior, Perus, ",
    "Rua Rio Bravo, Perus, ",
    "Rua Rio Colorado, Perus, ",
    "Rua Rio Jundiai, Perus, ",
    "Rua Rio Yukon, Perus, ",
    "Rua Roque Callage, Perus, ",
    "Rua Rosa do Japão, Perus, ",
    "Rua Rosinda, Perus, ",
    "Rua Rouxinol, Perus, ",
    "Rua Salles Gomes, Perus, ",
    "Rua Santa Cruz, Perus, ",
    "Rua Santa Gertrúdes, Perus, ",
    "Rua Santina, Perus, ",
    "Rua Santo Soncin, Perus, ",
    "Rua São Mateus, Perus, ",
    "Rua São Paulo, Perus, ",
    "Rua Sertão de Canudos, Perus, ",
    "Rua Silverânia, Perus, ",
    "Rua Sorano, Perus, ",
    "Rua Sucre, Perus, ",
    "Rua Taipoca, Perus, ",
    "Rua Tarcon, Perus, ",
    "Rua Telma, Perus, ",
    "Rua Tiburno, Perus, ",
    "Rua Tico Tico, Perus, ",
    "Rua Tito LIra, Perus, ",
    "Rua Tomas Xavier de Almeida, Perus, ",
    "Rua Tribuno, Perus, ",
    "Rua União, Perus, ",
    "Rua Vicente Licinio Cardoso, Perus, ",
    "Rua Violeta dos Alpes, Perus, ",
    "Rua Violeta Silvestre, Perus, ",
    "Rua Virgílio Paltrinieri, Perus, ",
    "Rua Visconti Coaracy, Perus, ",
    "Rua Vitória, Perus, ",
    "Rua Xavier de Castro, Perus, ",
    "Rua Ximburetinga, Perus, ",
    "Rua Xororo, Perus, ",
    "Rua Ylídio Figueiredo, Perus, ",
    "Travessa Antule Branco, Perus, ",
    "Travessa Attílio Torterelli Filho, Perus, ",
    "Travessa Ayrton Senna, Perus, ",
    "Travessa Begônia Rosada, Perus, ",
    "Travessa Begonias, Perus, ",
    "Travessa Brinco de Princesa, Perus, ",
    "Travessa Camélia, Perus, ",
    "Travessa Cambaratiba, Perus, ",
    "Travessa Cameleiro, Perus, ",
    "Travessa Coronel Julião de Moura Negrão, Perus, ",
    "Travessa da Liberdade, Perus, ",
    "Travessa das Acácias, Perus, ",
    "Travessa das Acácias Lilases, Perus, ",
    "Travessa das Adalias, Perus, ",
    "Travessa das Aves, Perus, ",
    "Travessa das Hortências, Perus, ",
    "Travessa das Hortências Roxas, Perus, ",
    "Travessa das Oliveiras, Perus, ",
    "Travessa das Orquídeas, Perus, ",
    "Travessa das Papoula, Perus, ",
    "Travessa das Resedas, Perus, ",
    "Travessa das Rosas, Perus, ",
    "Travessa das Tulipas, Perus, ",
    "Travessa das Tulipas Holandesas, Perus, ",
    "Travessa das Violetas, Perus, ",
    "Travessa das Violetas Azuis, Perus, ",
    "Travessa do Ipanema, Perus, ",
    "Travessa do Jacare, Perus, ",
    "Travessa dos Diamantes, Perus, ",
    "Travessa dos Fernandes, Perus, ",
    "Travessa dos Ipês, Perus, ",
    "Travessa dos Jasmins, Perus, ",
    "Travessa dos Lírios, Perus, ",
    "Travessa dos Lirios Amarelos, Perus, ",
    "Travessa dos Manacás, Perus, ",
    "Travessa Doze de Outubro, Perus, ",
    "Travessa Flor de Cactus, Perus, ",
    "Travessa Girassol, Perus, ",
    "Travessa Ipanema, Perus, ",
    "Travessa Jasmim do Campo, Perus, ",
    "Travessa Jordão, Perus, ",
    "Travessa José de Oliveira, Perus, ",
    "Travessa Laurentina Camargo Fanton, Perus, ",
    "Travessa Nova Flor, Perus, ",
    "Travessa Olivença, Perus, ",
    "Travessa Paulo Freire, Perus, ",
    "Travessa Petúnia, Perus, ",
    "Travessa Samambaia do Amazonas, Perus, ",
    "Travessa Savuru, Perus, ",
    "Travessa Sete de Setembro, Perus, ",
    "Travessa Tabuleiros de Valença, Perus, ",
    "Travessa Taia, Perus, ",
    "Travessa Tancredo Neves, Perus, ",
    "Travessa Vitória Régia, Perus, ",
    "Travessa Vitório Pellini, Perus, ",
    "Travessa Wilson Grey, Perus, ",
    "Trilha da Ferrovia, Perus, ",
    "Via de Pedestre Lírio-Azul, Perus, ",
    "Viaduto Deputado Ulysses Guimarães, Perus, ",
    "Viaduto Dona Mora Guimarães, Perus, ",
    "Viela Alejo Carpentier, Perus, ",
    "Viela das Azaleias, Perus, ",
    "Viela das Hortências, Perus, ",
    "Viela do Campo de Futebol, Perus, ",
    "Viela Dois da Rua Silveirânia, Perus, ",
    "Viela Dom Fernandes, Perus, ",
    "Viela dos Alpes, Perus, ",
    "Viela Joaquim Veríssimo Neto, Perus, ",
    "Viela Jota, Perus, ",
    "Viela Nahum Goldman, Perus, ",
    "Viela Um da Rua Silveirânia, Perus, "
]